# Generated by Django 5.2.7 on 2025-11-25 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0012_alter_partneraccounttrackeridentifier_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the endpoint (e.g., Get Traffic Source)', max_length=255)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', help_text='HTTP method for the request', max_length=10)),
                ('endpoint', models.CharField(help_text='API endpoint path (e.g., /api/v1/traffic)', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracker', models.ForeignKey(help_text='The tracker this endpoint belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='service_endpoints', to='integrations.tracker')),
            ],
            options={
                'verbose_name': 'Endpoint',
                'verbose_name_plural': 'Endpoints',
            },
        ),
    ]
