# Generated by Django 5.2.7 on 2025-11-25 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0002_serviceendpoint_visible_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the method (e.g., Get Account Name)', max_length=255)),
                ('return_key', models.CharField(blank=True, help_text='JSON key to return (e.g., data.name). Leave empty to return full response.', max_length=255, null=True)),
                ('arguments', models.JSONField(blank=True, default=list, help_text='List of arguments discovered from the endpoint URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_endpoint', models.ForeignKey(help_text='The endpoint this method uses', on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='service_builder.serviceendpoint')),
                ('visible_to', models.ManyToManyField(blank=True, help_text='Users who can view this method', related_name='visible_service_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Method',
                'verbose_name_plural': 'Methods',
            },
        ),
    ]
