# Generated by Django 5.2.7 on 2025-11-26 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0003_servicemethod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the scenario (e.g., Clone Campaign & Offer)', max_length=255)),
                ('arguments', models.JSONField(blank=True, default=list, help_text="List of arguments required by this scenario (e.g., ['source_campaign_id', 'geo'])")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible_to', models.ManyToManyField(blank=True, help_text='Users who can view this scenario', related_name='visible_scenarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scenario',
                'verbose_name_plural': 'Scenarios',
            },
        ),
        migrations.CreateModel(
            name='ScenarioStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of execution')),
                ('argument_mapping', models.JSONField(blank=True, default=dict, help_text="Mapping of method arguments to context variables (e.g., {'id': 'source_campaign_id'})")),
                ('output_variable_name', models.CharField(blank=True, help_text="Name of the variable to store the result in Context (e.g., 'new_campaign_id')", max_length=255)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scenario_steps', to='service_builder.servicemethod')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='service_builder.scenario')),
            ],
            options={
                'verbose_name': 'Scenario Step',
                'verbose_name_plural': 'Scenario Steps',
                'ordering': ['order'],
            },
        ),
    ]
