# Generated by Django 5.2.7 on 2025-11-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0004_scenario_scenariostep'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariostep',
            name='response_modification',
            field=models.JSONField(blank=True, default=dict, help_text="Modifications to apply to the response JSON (e.g., {'name': 'new_name_var'})"),
        ),
    ]
