# Generated by Django 5.2.7 on 2025-11-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0005_scenariostep_response_modification'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceendpoint',
            name='is_valid',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
