# Generated by Django 5.2.7 on 2025-11-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0006_serviceendpoint_is_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceendpoint',
            name='is_valid',
        ),
        migrations.AddField(
            model_name='scenario',
            name='is_valid',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
