# Generated by Django 5.2.7 on 2025-11-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0007_remove_serviceendpoint_is_valid_scenario_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariostep',
            name='success_condition',
            field=models.TextField(blank=True, help_text="Python-like expression to validate the result (e.g., result['status'] == 'success'). Available variables: result, context."),
        ),
        migrations.AlterField(
            model_name='scenariostep',
            name='response_modification',
            field=models.JSONField(blank=True, default=dict, help_text="Map internal JSON paths to context variables (e.g. {'data.id': 'new_id'})."),
        ),
    ]
