# Generated by Django 5.2.7 on 2025-11-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0008_scenariostep_success_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariostep',
            name='condition_error_message',
            field=models.CharField(blank=True, help_text='Message to display if the condition fails.', max_length=255),
        ),
    ]
