# Generated by Django 5.2.7 on 2025-11-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0009_scenariostep_condition_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariostep',
            name='context_extraction',
            field=models.JSONField(blank=True, default=dict, help_text='Extract data from result into context variables. Format: {\'var_name\': \'expression\'}. Example: {\'first_id\': \'result[0]["id"]\'}.'),
        ),
        migrations.AlterField(
            model_name='scenariostep',
            name='response_modification',
            field=models.JSONField(blank=True, default=dict, help_text="Map internal JSON paths to context variables (e.g. {'data.id': 'new_id'}). Injects context values INTO the response.", verbose_name='Response Injection'),
        ),
    ]
