# Generated by Django 5.2.7 on 2025-12-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0010_scenariostep_context_extraction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemethod',
            name='payload_fields',
            field=models.JSONField(blank=True, default=list, help_text="List of fields to be constructed in the JSON body (e.g. ['body.name', 'body.data.id'])"),
        ),
    ]
