# Generated by Django 5.2.7 on 2025-12-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0011_servicemethod_payload_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemethod',
            name='payload_fields',
            field=models.JSONField(blank=True, default=list, help_text="List of fields to be constructed in the JSON body (e.g. ['body.name', 'body.data.id'])", null=True),
        ),
    ]
