# Generated by Django 5.2.7 on 2025-12-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0012_alter_servicemethod_payload_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='is_valid',
        ),
        migrations.AddField(
            model_name='scenario',
            name='validation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid')], default='PENDING', editable=False, help_text='Status of the scenario validation based on the last test run.', max_length=10),
        ),
    ]
