# Generated by Django 5.2.7 on 2025-12-13 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0013_remove_scenario_is_valid_scenario_validation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariostep',
            name='action_config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration for the action (e.g. Merge keys, inputs). Format: JSON.'),
        ),
        migrations.AddField(
            model_name='scenariostep',
            name='action_type',
            field=models.CharField(blank=True, choices=[('MERGE', 'Merge List')], help_text='Type of action to perform (if Step Type is Action)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scenariostep',
            name='step_type',
            field=models.CharField(choices=[('API_CALL', 'API Call'), ('ACTION', 'Action')], default='API_CALL', help_text='Type of step: API Call (HTTP Request) or Action (Data Processing)', max_length=20),
        ),
        migrations.AlterField(
            model_name='scenariostep',
            name='method',
            field=models.ForeignKey(blank=True, help_text='The Service Method to call (Required if Step Type is API Call)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scenario_steps', to='service_builder.servicemethod'),
        ),
    ]
