# Generated by Django 5.2.7 on 2025-12-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0014_scenariostep_action_config_scenariostep_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariostep',
            name='auth_context_variable',
            field=models.CharField(blank=True, default='auth_id', help_text="Name of the Context Variable that contains the ApiAuthID to use for this step. Defaults to 'auth_id'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='scenariostep',
            name='action_type',
            field=models.CharField(blank=True, choices=[('MERGE', 'Merge List'), ('FILTER', 'Filter List')], help_text='Type of action to perform (if Step Type is Action)', max_length=50, null=True),
        ),
    ]
