# Generated by Django 5.2.7 on 2025-12-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0015_scenariostep_auth_context_variable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariostep',
            name='context_extraction',
            field=models.JSONField(blank=True, default=dict, help_text='Extract data from result into context variables. Format: {\'var_name\': \'expression\'}. Example: {\'first_id\': \'result[0]["id"]\'}.', null=True),
        ),
    ]
