# Generated by Django 5.2.7 on 2025-12-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0016_alter_scenariostep_context_extraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariostep',
            name='action_type',
            field=models.CharField(blank=True, choices=[('MERGE', 'Merge List'), ('FILTER', 'Filter List'), ('TRANSFORM', 'Transform Data')], help_text='Type of action to perform (if Step Type is Action)', max_length=50, null=True),
        ),
    ]
