# Generated by Django 5.2.7 on 2025-12-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0017_alter_scenariostep_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariostep',
            name='iterator_variable',
            field=models.CharField(blank=True, help_text="Variable name of the list to iterate over (e.g. 'campaigns'). If set, this step runs for each item.", max_length=255, null=True),
        ),
    ]
