# Generated by Django 5.2.7 on 2025-12-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0018_scenariostep_iterator_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariostep',
            name='action_type',
            field=models.CharField(blank=True, choices=[('MERGE', 'Merge List'), ('FILTER', 'Filter List'), ('TRANSFORM', 'Transform Data'), ('ENRICH', 'Enrich List (Join & Append)')], help_text='Type of action to perform (if Step Type is Action)', max_length=50, null=True),
        ),
    ]
