# Generated by Django 5.2.7 on 2025-12-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0019_alter_scenariostep_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariostep',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to temporarily disable this step during testing.'),
        ),
        migrations.AlterField(
            model_name='scenariostep',
            name='iterator_variable',
            field=models.CharField(blank=True, help_text="Variable name of the list to iterate over (e.g. 'campaigns'). If set, this step runs for each item.", max_length=100, null=True),
        ),
    ]
