# Generated by Django 5.2.7 on 2025-12-23 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0020_scenariostep_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='return_variables',
            field=models.JSONField(blank=True, default=list, help_text="List of context variables to return as the final output (e.g., ['created_campaign_ids'])"),
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the workflow (e.g., Publisher Onboarding)', max_length=255)),
                ('arguments', models.JSONField(blank=True, default=list, help_text="List of global input arguments required by this workflow (e.g., ['url', 'geo'])")),
                ('return_variables', models.JSONField(blank=True, default=list, help_text="List of final output variables to return from the workflow (e.g., ['created_campaigns'])")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible_to', models.ManyToManyField(blank=True, help_text='Users who can view this workflow', related_name='visible_workflows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('argument_mapping', models.JSONField(blank=True, default=dict, help_text="Map Workflow Context variables to Scenario Arguments. format: {'arg_name': '{{ context_var }}'}")),
                ('iterator_variable', models.CharField(blank=True, help_text='Context variable name (list) to iterate over. The Scenario will run for each item.', max_length=100, null=True)),
                ('output_variable_name', models.CharField(blank=True, help_text='Name of variable to store the result in Workflow Context.', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to skip this step.')),
                ('scenario', models.ForeignKey(help_text='The Scenario to execute in this step', on_delete=django.db.models.deletion.PROTECT, to='service_builder.scenario')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='service_builder.workflow')),
            ],
            options={
                'verbose_name': 'Workflow Step',
                'verbose_name_plural': 'Workflow Steps',
                'ordering': ['order'],
            },
        ),
    ]
