# Generated by Django 5.2.7 on 2025-12-23 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0021_scenario_return_variables_workflow_workflowstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='router_variable',
            field=models.CharField(blank=True, help_text="Context variable to check for Dynamic Routing (e.g. 'tracker_type').", max_length=255),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='routing_map',
            field=models.JSONField(blank=True, default=dict, help_text="Map variable values to Scenario IDs. Format: {'TrafficGold': 12, 'Voluum': 15}."),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='scenario',
            field=models.ForeignKey(blank=True, help_text='Default Scenario to execute. Required if no routing logic is defined or matches.', null=True, on_delete=django.db.models.deletion.PROTECT, to='service_builder.scenario'),
        ),
    ]
