# Generated by Django 5.2.7 on 2025-12-23 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0015_apiauthtype_inject_in_apiauthtype_inject_key_and_more'),
        ('service_builder', '0022_workflowstep_router_variable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the Abstract Action (e.g. 'Create Campaign')", max_length=255, unique=True)),
                ('code', models.SlugField(help_text="Unique code for this action (e.g. 'create_campaign')", max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='business_action',
            field=models.ForeignKey(blank=True, help_text='Abstract Business Action to perform (resolves to a Scenario based on Tracker).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_builder.businessaction'),
        ),
        migrations.CreateModel(
            name='BusinessActionVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='service_builder.businessaction')),
                ('scenario', models.ForeignKey(help_text='Scenario that implements this action.', on_delete=django.db.models.deletion.PROTECT, to='service_builder.scenario')),
                ('tracker', models.ForeignKey(help_text='Tracker for which this scenario is applicable.', on_delete=django.db.models.deletion.PROTECT, to='integrations.tracker')),
            ],
            options={
                'unique_together': {('business_action', 'tracker')},
            },
        ),
    ]
