# Generated by Django 5.2.7 on 2025-12-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0023_businessaction_workflowstep_business_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaction',
            name='validation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid')], default='PENDING', help_text='Status of the action validation.', max_length=10),
        ),
        migrations.AddField(
            model_name='serviceendpoint',
            name='validation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid')], default='PENDING', help_text='Status of the entity validation.', max_length=10),
        ),
        migrations.AddField(
            model_name='servicemethod',
            name='validation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid')], default='PENDING', help_text='Status of the entity validation.', max_length=10),
        ),
        migrations.AddField(
            model_name='workflow',
            name='validation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid')], default='PENDING', help_text='Status of the workflow validation.', max_length=10),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='validation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid')], default='PENDING', help_text='Status of the scenario validation based on the last test run.', max_length=10),
        ),
    ]
