# Generated by Django 5.2.7 on 2025-12-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0024_businessaction_validation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceendpoint',
            name='parameters',
            field=models.JSONField(blank=True, default=list, help_text="List of query parameters (e.g., ['dateFrom', 'dateTo'])"),
        ),
        migrations.AddField(
            model_name='serviceendpoint',
            name='resource_path',
            field=models.CharField(blank=True, help_text='Invariant part of the URL (e.g., /api/v1/traffic)', max_length=255),
        ),
        migrations.AlterField(
            model_name='serviceendpoint',
            name='endpoint',
            field=models.CharField(help_text='Full API endpoint path (Auto-generated)', max_length=500),
        ),
    ]
