# Generated by Django 5.2.7 on 2026-01-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0025_serviceendpoint_parameters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaction',
            name='arguments',
            field=models.JSONField(blank=True, default=list, help_text="List of arguments required by this action (e.g., ['campaign_name', 'offer_id'])"),
        ),
    ]
