# Generated by Django 5.2.7 on 2026-01-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0026_businessaction_arguments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaction',
            name='validation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid')], default='PENDING', help_text='Status of the entity validation.', max_length=10),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='validation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid')], default='PENDING', help_text='Status of the entity validation.', max_length=10),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='validation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid')], default='PENDING', help_text='Status of the entity validation.', max_length=10),
        ),
    ]
