# Generated by Django 5.2.7 on 2026-01-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0027_alter_businessaction_validation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaction',
            name='output_variables',
            field=models.JSONField(blank=True, default=list, help_text="List of output variables provided by this action (e.g., ['campaign_id', 'url'])"),
        ),
        migrations.AddField(
            model_name='businessactionvariant',
            name='input_mapping',
            field=models.JSONField(blank=True, default=dict, help_text='Map Business Action Args to Scenario Args. Key=ScenarioArg (Target), Val={{ActionArg}} (Source)'),
        ),
        migrations.AddField(
            model_name='businessactionvariant',
            name='output_mapping',
            field=models.JSONField(blank=True, default=dict, help_text='Map Scenario Results to Business Action Outputs. Key=ActionOutput (Target), Val={{ScenarioReturn}} (Source)'),
        ),
    ]
