# Generated by Django 5.2.7 on 2026-01-13 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0028_businessaction_output_variables_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='return_variables',
        ),
    ]
