# Generated by Django 5.2.7 on 2026-01-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0029_remove_scenario_return_variables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='arguments',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='return_variables',
        ),
        migrations.RemoveField(
            model_name='workflowstep',
            name='argument_mapping',
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='input_mapping',
            field=models.JSONField(blank=True, default=dict, help_text="Map Workflow Context variables to Action Arguments. format: {'action_arg': '{{ context_var }}'}"),
        ),
    ]
