# Generated by Django 5.2.7 on 2026-01-21 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0030_remove_workflow_arguments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowstep',
            name='router_variable',
        ),
        migrations.RemoveField(
            model_name='workflowstep',
            name='routing_map',
        ),
    ]
