# Generated by Django 5.2.7 on 2026-01-24 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0031_remove_workflowstep_router_variable_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaction',
            name='visible_to',
            field=models.ManyToManyField(blank=True, help_text='Users who can view this action', related_name='visible_business_actions', to=settings.AUTH_USER_MODEL),
        ),
    ]
