# Generated by Django 5.2.7 on 2026-01-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0032_businessaction_visible_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceendpoint',
            name='api_configuration',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration for API data formatting (e.g. date formats, modifiers)'),
        ),
    ]
