# Generated by Django 5.2.7 on 2026-02-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0033_serviceendpoint_api_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaction',
            name='validation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid'), ('TEST', 'Test (Manual Only)')], default='PENDING', help_text='Status of the entity validation.', max_length=10),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='validation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid'), ('TEST', 'Test (Manual Only)')], default='PENDING', help_text='Status of the entity validation.', max_length=10),
        ),
        migrations.AlterField(
            model_name='serviceendpoint',
            name='validation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid'), ('TEST', 'Test (Manual Only)')], default='PENDING', help_text='Status of the entity validation.', max_length=10),
        ),
        migrations.AlterField(
            model_name='servicemethod',
            name='validation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid'), ('TEST', 'Test (Manual Only)')], default='PENDING', help_text='Status of the entity validation.', max_length=10),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='validation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid'), ('TEST', 'Test (Manual Only)')], default='PENDING', help_text='Status of the entity validation.', max_length=10),
        ),
    ]
