# Generated by Django 5.2.7 on 2026-02-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0034_alter_businessaction_validation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='arguments',
            field=models.JSONField(blank=True, default=list, help_text='Define arguments required to start this workflow. These will be available in the initial context.'),
        ),
    ]
