# Generated by Django 5.2.7 on 2026-02-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0035_workflow_arguments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariostep',
            name='action_type',
            field=models.CharField(blank=True, choices=[('MERGE', 'Merge List'), ('FILTER', 'Filter List'), ('TRANSFORM', 'Transform Data'), ('ENRICH', 'Enrich List (Join & Append)'), ('HIERARCHICAL_FLATTEN', 'Hierarchical Flatten (Parent→Child)'), ('GROUP_BY', 'Group By (Aggregate)')], help_text='Type of action to perform (if Step Type is Action)', max_length=50, null=True),
        ),
    ]
