# Generated by Django 5.2.7 on 2026-03-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0039_add_multi_hierarchical_flatten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariostep',
            name='action_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('MERGE', 'Merge List'),
                    ('FILTER', 'Filter List'),
                    ('TRANSFORM', 'Transform Data'),
                    ('ENRICH', 'Enrich List (Join & Append)'),
                    ('HIERARCHICAL_FLATTEN', 'Hierarchical Flatten (Parent→Child)'),
                    ('MULTI_HIERARCHICAL_FLATTEN', 'Multi-Hierarchical Flatten (N levels)'),
                    ('GROUP_BY', 'Group By (Aggregate)'),
                    ('FLATTEN_COLLECTION', 'Flatten Collection (Expand List Field)'),
                    ('FIND_OIDH', 'Find OIDH'),
                ],
                help_text='Type of action to perform (if Step Type is Action)',
                max_length=50,
                null=True,
            ),
        ),
    ]
