# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0042_add_dict_to_list_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariostep',
            name='error_handlers',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="For API Call: list of handlers for non-2xx responses. Each: status_codes, body_match (optional), action (return_body|return_value), value (if return_value). Empty = current behaviour (raise).",
            ),
        ),
    ]
