# Generated by Django 5.2.7 on 2026-04-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0044_action_config_library'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionconfiglibrary',
            options={'ordering': ['action_type', 'name'], 'verbose_name': 'Action config library entry', 'verbose_name_plural': 'Action config library'},
        ),
        migrations.RemoveField(
            model_name='actionconfiglibrary',
            name='sort_order',
        ),
    ]
