# Generated by Django 5.2.7 on 2026-04-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0045_remove_action_config_library_sort_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessaction',
            name='code',
        ),
    ]
