# Generated by Django 5.2.7 on 2026-04-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0046_remove_businessaction_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionconfiglibrary',
            name='action_type',
            field=models.CharField(choices=[('MERGE', 'Merge List'), ('FILTER', 'Filter List'), ('TRANSFORM', 'Transform Data'), ('DIFF_OBJECTS', 'Diff Objects'), ('ENRICH', 'Enrich List (Join & Append)'), ('HIERARCHICAL_FLATTEN', 'Hierarchical Flatten (Parent→Child)'), ('MULTI_HIERARCHICAL_FLATTEN', 'Multi-Hierarchical Flatten (N levels)'), ('GROUP_BY', 'Group By (Aggregate)'), ('FLATTEN_COLLECTION', 'Flatten Collection (Expand List Field)'), ('FIND_OIDH', 'Find OIDH'), ('BUILD_OIDH_BLACKLIST', 'Build OIDH Blacklist'), ('DICT_TO_LIST', 'Dict to List')], help_text='Must match an ActionRunner action type.', max_length=50),
        ),
        migrations.AlterField(
            model_name='scenariostep',
            name='action_type',
            field=models.CharField(blank=True, choices=[('MERGE', 'Merge List'), ('FILTER', 'Filter List'), ('TRANSFORM', 'Transform Data'), ('DIFF_OBJECTS', 'Diff Objects'), ('ENRICH', 'Enrich List (Join & Append)'), ('HIERARCHICAL_FLATTEN', 'Hierarchical Flatten (Parent→Child)'), ('MULTI_HIERARCHICAL_FLATTEN', 'Multi-Hierarchical Flatten (N levels)'), ('GROUP_BY', 'Group By (Aggregate)'), ('FLATTEN_COLLECTION', 'Flatten Collection (Expand List Field)'), ('FIND_OIDH', 'Find OIDH'), ('BUILD_OIDH_BLACKLIST', 'Build OIDH Blacklist'), ('DICT_TO_LIST', 'Dict to List')], help_text='Type of action to perform (if Step Type is Action)', max_length=50, null=True),
        ),
    ]
