# Generated by Django 5.2.7 on 2026-05-11 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_builder', '0053_merge_tree_stats_versions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actionconfiglibrary',
            name='visible_to',
            field=models.ManyToManyField(blank=True, help_text='Users who can view and use this action config library entry.', related_name='visible_action_config_libraries', to=settings.AUTH_USER_MODEL),
        ),
    ]
