# Generated by Django 5.2.7 on 2025-12-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TargetParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the parameter (e.g. 'Country')", max_length=255, unique=True)),
                ('values', models.JSONField(blank=True, default=list, help_text="List of predefined values (e.g. ['US', 'UK', 'CA'])")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Target Parameter',
                'verbose_name_plural': 'Target Parameters',
            },
        ),
    ]
