# Generated by Django 5.2.7 on 2026-01-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the configuration (e.g. 'Publisher A')", max_length=255)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Configuration state for parameters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Publisher Config',
                'verbose_name_plural': 'Publisher Configs',
            },
        ),
    ]
