# Generated by Django 5.2.7 on 2026-01-03 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0015_apiauthtype_inject_in_apiauthtype_inject_key_and_more'),
        ('metadata', '0002_publisherconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisherconfig',
            name='name',
        ),
        migrations.AddField(
            model_name='publisherconfig',
            name='partner_account',
            field=models.OneToOneField(blank=True, help_text='Select a Publisher Account to configure', limit_choices_to={'account_type__name': 'Publisher'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher_config', to='integrations.partneraccount'),
        ),
    ]
