# Generated by Django 5.2.7 on 2026-01-03 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0015_apiauthtype_inject_in_apiauthtype_inject_key_and_more'),
        ('metadata', '0003_remove_publisherconfig_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisherconfig',
            name='is_locked',
            field=models.BooleanField(default=True, help_text='Uncheck to edit configuration. Automatically locks on save.'),
        ),
        migrations.AlterField(
            model_name='publisherconfig',
            name='partner_account',
            field=models.OneToOneField(help_text='Select a Publisher Account to configure', limit_choices_to={'account_type__name': 'Publisher'}, on_delete=django.db.models.deletion.CASCADE, related_name='publisher_config', to='integrations.partneraccount'),
        ),
    ]
