# Generated by Django 5.2.7 on 2026-01-06 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0004_publisherconfig_is_locked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibilityMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_value', models.CharField(help_text="The value of the subject parameter that triggers the rule (e.g., 'iOS')", max_length=255)),
                ('allowed_values', models.JSONField(default=list, help_text="List of allowed values for the target parameter (e.g., ['Mobile', 'Tablet'])")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_parameter', models.ForeignKey(help_text="The parameter that triggers the rule (e.g., 'OS')", on_delete=django.db.models.deletion.CASCADE, related_name='rules_as_subject', to='metadata.targetparameter')),
                ('target_parameter', models.ForeignKey(help_text="The parameter being restricted (e.g., 'Device Type')", on_delete=django.db.models.deletion.CASCADE, related_name='rules_as_target', to='metadata.targetparameter')),
            ],
            options={
                'verbose_name': 'Compatibility Rule',
                'verbose_name_plural': 'Compatibility Matrix',
                'unique_together': {('subject_parameter', 'subject_value', 'target_parameter')},
            },
        ),
    ]
