# Generated by Django 5.2.7 on 2026-01-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_compatibilitymatrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='compatibilitymatrix',
            name='is_locked',
            field=models.BooleanField(default=True, help_text='Uncheck to edit rule. Automatically locks on save.'),
        ),
    ]
