# Generated by Django 5.2.7 on 2026-01-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0006_compatibilitymatrix_is_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Traffic Type',
                'verbose_name_plural': 'Traffic Types',
                'ordering': ['name'],
            },
        ),
    ]
