# Generated by Django 5.2.7 on 2026-01-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0007_traffictype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Configuration key (e.g. 'date_input_formats')", max_length=255, unique=True)),
                ('value', models.JSONField(default=dict, help_text='Configuration value (JSON)')),
                ('description', models.TextField(blank=True, help_text='Description of what this setting controls')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
            },
        ),
    ]
