# Generated by Django 5.2.7 on 2026-01-27 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0008_systemconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemConfig',
        ),
    ]
