# Generated by Django 5.2.7 on 2026-01-30 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0018_systemconfig'),
        ('metadata', '0009_delete_systemconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the standard system variable (e.g. 'std_subid')", max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this variable represents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Variable',
                'verbose_name_plural': 'Global Variables',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrackerResponseMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_key', models.CharField(help_text="Key in the tracker response JSON (e.g. 'click_id' or 'data.id'). Supports dot notation.", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('global_variable', models.ForeignKey(help_text='The standard variable being mapped', on_delete=django.db.models.deletion.CASCADE, related_name='tracker_mappings', to='metadata.globalvariable')),
                ('tracker', models.ForeignKey(help_text='The Tracker this mapping applies to', on_delete=django.db.models.deletion.CASCADE, related_name='response_mappings', to='integrations.tracker')),
            ],
            options={
                'verbose_name': 'Tracker Response Mapping',
                'verbose_name_plural': 'Tracker Response Mappings',
                'unique_together': {('tracker', 'global_variable')},
            },
        ),
    ]
