# Generated by Django 5.2.7 on 2026-01-30 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0018_systemconfig'),
        ('metadata', '0010_globalvariable_trackerresponsemapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping', models.JSONField(blank=True, default=dict, help_text="Configuration state: {'GlobalVarName': 'TrackerKey'}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracker', models.OneToOneField(help_text='Select a Tracker to configure', on_delete=django.db.models.deletion.CASCADE, related_name='tracker_config', to='integrations.tracker')),
            ],
            options={
                'verbose_name': 'Tracker Response Mapping',
                'verbose_name_plural': 'Tracker Response Mappings',
            },
        ),
        migrations.DeleteModel(
            name='TrackerResponseMapping',
        ),
    ]
