# Generated by Django 5.2.7 on 2026-01-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0011_trackerconfig_delete_trackerresponsemapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackerconfig',
            name='is_locked',
            field=models.BooleanField(default=True, help_text='Uncheck to edit configuration. Automatically locks on save.'),
        ),
    ]
