# Generated by Django 5.2.7 on 2026-04-15 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0012_trackerconfig_is_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentAttributeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Segments Attribute Type',
                'verbose_name_plural': 'Segments Attributes Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SegmentAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute_type', models.ForeignKey(help_text='Type from Segments Attributes Types', on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='metadata.segmentattributetype')),
            ],
            options={
                'verbose_name': 'Segments Attribute',
                'verbose_name_plural': 'Segments Attributes',
                'ordering': ['name'],
            },
        ),
    ]
