# Generated by Django 5.2.7 on 2026-05-11 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0013_segment_attributes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compatibilitymatrix',
            name='visible_to',
            field=models.ManyToManyField(blank=True, help_text='Users who can view and use this compatibility rule.', related_name='visible_compatibility_matrices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='globalvariable',
            name='visible_to',
            field=models.ManyToManyField(blank=True, help_text='Users who can view and use this global variable.', related_name='visible_global_variables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publisherconfig',
            name='visible_to',
            field=models.ManyToManyField(blank=True, help_text='Users who can view and use this publisher config.', related_name='visible_publisher_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='segmentattribute',
            name='visible_to',
            field=models.ManyToManyField(blank=True, help_text='Users who can view and use this segment attribute.', related_name='visible_segment_attributes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='segmentattributetype',
            name='visible_to',
            field=models.ManyToManyField(blank=True, help_text='Users who can view and use this segment attribute type.', related_name='visible_segment_attribute_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='targetparameter',
            name='visible_to',
            field=models.ManyToManyField(blank=True, help_text='Users who can view and use this target parameter.', related_name='visible_target_parameters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trackerconfig',
            name='visible_to',
            field=models.ManyToManyField(blank=True, help_text='Users who can view and use this tracker response mapping.', related_name='visible_tracker_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traffictype',
            name='visible_to',
            field=models.ManyToManyField(blank=True, help_text='Users who can view and use this traffic type.', related_name='visible_traffic_types', to=settings.AUTH_USER_MODEL),
        ),
    ]
