# Generated by Django 5.2.7 on 2026-06-01 08:37

import django.db.models.deletion
import metadata.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0021_alter_tracker_options_systemconfig_visible_to'),
        ('metadata', '0014_compatibilitymatrix_visible_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Label for this spec (e.g. "Admin API v2").', max_length=255)),
                ('spec_file', models.FileField(help_text='Upload the API specification file from your computer.', upload_to=metadata.models.api_spec_upload_to)),
                ('source_filename', models.CharField(blank=True, help_text='Original filename as uploaded by the user.', max_length=512)),
                ('format', models.CharField(choices=[('openapi', 'OpenAPI (YAML)'), ('json', 'JSON'), ('markdown', 'Markdown'), ('plain', 'Plain text'), ('html', 'HTML'), ('unknown', 'Unknown')], default='unknown', help_text='Detected or assigned format hint for agents.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracker', models.ForeignKey(help_text='Platform (tracker) this specification belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='api_specs', to='integrations.tracker')),
                ('visible_to', models.ManyToManyField(blank=True, help_text='Users who can view and use this API spec.', related_name='visible_api_specs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Spec',
                'verbose_name_plural': 'API Specs',
                'ordering': ['tracker__name', 'name'],
                'unique_together': {('tracker', 'name')},
            },
        ),
    ]
