# Generated by Django 5.2.7 on 2025-11-21 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAuthType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the authentication type (e.g., 'OAuth2', 'API Key')", max_length=255, unique=True)),
                ('key_definitions', models.JSONField(blank=True, default=list, help_text="List of key names required for this auth type (e.g., ['api_key'] or ['username', 'password'])")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible_to', models.ManyToManyField(blank=True, help_text='Users who can view and use this authentication type.', related_name='visible_auth_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Authentication Type',
                'verbose_name_plural': 'API Authentication Types',
            },
        ),
    ]
