# Generated by Django 5.2.7 on 2025-11-21 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_tracker_alter_apiauthtype_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAuthID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(help_text='Account to which you connect with the API', max_length=255)),
                ('request_url', models.URLField(help_text='The base URL for requests')),
                ('credentials_encrypted', models.TextField(blank=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auth_ids', to='integrations.apiauthtype')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_ids', to='integrations.tracker')),
                ('visible_to', models.ManyToManyField(blank=True, related_name='accessible_auth_ids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Auth ID',
                'verbose_name_plural': 'API Auth IDs',
            },
        ),
    ]
