# Generated by Django 5.2.7 on 2025-11-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_apiauthid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiauthid',
            name='credentials_encrypted',
            field=models.TextField(blank=True),
        ),
    ]
