# Generated by Django 5.2.7 on 2025-11-24 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_alter_apiauthid_credentials_encrypted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='visible_to',
            field=models.ManyToManyField(blank=True, related_name='accessible_trackers', to=settings.AUTH_USER_MODEL),
        ),
    ]
