# Generated by Django 5.2.7 on 2025-11-24 16:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_tracker_visible_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the partner account', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible_to', models.ManyToManyField(blank=True, related_name='accessible_partner_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner Account',
                'verbose_name_plural': 'Partner Accounts',
            },
        ),
    ]
