# Generated by Django 5.2.7 on 2025-11-24 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_partneraccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partneraccount',
            options={'verbose_name': 'Partner Account ID', 'verbose_name_plural': 'Partner Account IDs'},
        ),
    ]
