# Generated by Django 5.2.7 on 2025-11-24 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_alter_partneraccount_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerAccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the partner account type', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible_to', models.ManyToManyField(blank=True, related_name='accessible_partner_account_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner Account Type',
                'verbose_name_plural': 'Partner Account Types',
            },
        ),
    ]
