# Generated by Django 5.2.7 on 2025-11-24 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_partneraccounttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='partneraccount',
            name='account_type',
            field=models.ForeignKey(help_text='Type of the partner account', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_accounts', to='integrations.partneraccounttype'),
        ),
    ]
