# Generated by Django 5.2.7 on 2025-11-24 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_partneraccount_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerAccountTrackerIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id_in_tracker', models.CharField(help_text='ID of this account in the specific tracker', max_length=255)),
                ('account_name_in_tracker', models.CharField(default='TO_BE_DONE_SOON', help_text='Name of this account in the specific tracker (fetched from API)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_identifiers', to='integrations.partneraccount')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_identifiers', to='integrations.tracker')),
            ],
            options={
                'verbose_name': 'Tracker Identifier',
                'verbose_name_plural': 'Tracker Identifiers',
                'unique_together': {('partner_account', 'tracker')},
            },
        ),
    ]
