# Generated by Django 5.2.7 on 2025-11-25 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0010_partneraccounttrackeridentifier'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partneraccounttrackeridentifier',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='partneraccounttrackeridentifier',
            name='api_auth_id',
            field=models.ForeignKey(help_text='The specific API connection (Tracker + Credentials) where this partner exists.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_identifiers', to='integrations.apiauthid'),
        ),
        migrations.RemoveField(
            model_name='partneraccounttrackeridentifier',
            name='tracker',
        ),
    ]
