# Generated by Django 5.2.7 on 2025-11-25 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0011_alter_partneraccounttrackeridentifier_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partneraccounttrackeridentifier',
            unique_together={('partner_account', 'api_auth_id')},
        ),
    ]
