# Generated by Django 5.2.7 on 2025-11-25 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0012_alter_partneraccounttrackeridentifier_unique_together'),
        ('service_builder', '0003_servicemethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='partneraccounttrackeridentifier',
            name='identifying_method',
            field=models.ForeignKey(blank=True, help_text='Method used to fetch the account name automatically', null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_builder.servicemethod'),
        ),
        migrations.AlterField(
            model_name='partneraccounttrackeridentifier',
            name='account_name_in_tracker',
            field=models.CharField(blank=True, help_text='Name of this account in the specific tracker (fetched from API)', max_length=255),
        ),
    ]
