# Generated by Django 5.2.7 on 2025-12-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0013_partneraccounttrackeridentifier_identifying_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partneraccount',
            name='domain',
            field=models.CharField(blank=True, help_text='Optional domain associated with this account (e.g., for publishers)', max_length=255, null=True),
        ),
    ]
