# Generated by Django 5.2.7 on 2025-12-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0014_partneraccount_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiauthtype',
            name='inject_in',
            field=models.CharField(blank=True, choices=[('HEADER', 'Header'), ('QUERY_PARAM', 'Query Parameter')], default='HEADER', help_text='Where to inject the token in the main request', max_length=20),
        ),
        migrations.AddField(
            model_name='apiauthtype',
            name='inject_key',
            field=models.CharField(blank=True, help_text="Key name for injection (e.g. 'Authorization' or 'api_key')", max_length=255),
        ),
        migrations.AddField(
            model_name='apiauthtype',
            name='login_payload',
            field=models.JSONField(blank=True, default=dict, help_text='JSON Body for Login. Use {{ username }} and {{ password }} as placeholders.'),
        ),
        migrations.AddField(
            model_name='apiauthtype',
            name='login_url',
            field=models.CharField(blank=True, help_text='URL to Login/Get Token (e.g. https://api.site.com/login). Supports {base_url}.', max_length=500),
        ),
        migrations.AddField(
            model_name='apiauthtype',
            name='token_path',
            field=models.CharField(blank=True, help_text='JSON Path to extract token from response (e.g. data.token or access_token)', max_length=255),
        ),
    ]
