# Generated by Django 5.2.7 on 2026-01-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0015_apiauthtype_inject_in_apiauthtype_inject_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiauthid',
            name='account_name',
            field=models.CharField(help_text='Account to which you connect with the API', max_length=255, unique=True),
        ),
    ]
