# Generated by Django 5.2.7 on 2026-01-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0016_alter_apiauthid_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='api_configuration',
            field=models.JSONField(blank=True, default=dict, help_text='Tracker-specific API configuration (e.g. output_formats)'),
        ),
    ]
