# Generated by Django 5.2.7 on 2026-04-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0019_apiauthtype_static_inject_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiauthid',
            name='request_url',
            field=models.URLField(help_text='The base URL for requests. Supports %credential_key% placeholders, for example: https://api.telegram.org/bot%token%.'),
        ),
        migrations.AlterField(
            model_name='apiauthtype',
            name='inject_in',
            field=models.CharField(blank=True, choices=[('HEADER', 'Header'), ('QUERY_PARAM', 'Query Parameter'), ('PATH_TEMPLATE', 'Path Template')], default='HEADER', help_text='Where to inject the token in the main request. PATH_TEMPLATE replaces %inject_key% in URL.', max_length=20),
        ),
        migrations.AlterField(
            model_name='apiauthtype',
            name='static_inject_in',
            field=models.CharField(blank=True, choices=[('HEADER', 'Header'), ('QUERY_PARAM', 'Query Parameter'), ('PATH_TEMPLATE', 'Path Template')], default='HEADER', help_text='For static credentials (key_definitions): where to inject keys into the main request. PATH_TEMPLATE replaces %key_name% placeholders in request URL.', max_length=20),
        ),
    ]
