# Generated by Django 5.2.7 on 2026-05-11 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0020_alter_apiauthid_request_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracker',
            options={'verbose_name': 'Tracker / Platform', 'verbose_name_plural': 'Trackers / Platforms'},
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='visible_to',
            field=models.ManyToManyField(blank=True, help_text='Users who can view and use this system configuration.', related_name='visible_system_configs', to=settings.AUTH_USER_MODEL),
        ),
    ]
