# Generated by Django 5.2.7 on 2026-02-24 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_builder', '0036_alter_scenariostep_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for this schedule (e.g., Every 6 hours)', max_length=255)),
                ('interval_unit', models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], help_text='Unit of the interval', max_length=20)),
                ('interval_value', models.PositiveIntegerField(default=1, help_text='Number of units between runs (e.g., 6 for every 6 hours)')),
                ('minute', models.PositiveSmallIntegerField(blank=True, help_text='Minute (0-59). Used for hours/days/weeks/months.', null=True)),
                ('hour', models.PositiveSmallIntegerField(blank=True, help_text='Hour (0-23). Used for days/weeks/months.', null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, help_text='Day of month (1-31). Used for months.', null=True)),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, help_text='Day of week (0-6, Sunday=0). Used for weeks.', null=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, help_text='Month (1-12). Used for monthly schedules.', null=True)),
            ],
            options={
                'verbose_name': 'Frequency',
                'verbose_name_plural': 'Frequencies',
            },
        ),
        migrations.CreateModel(
            name='ScheduledWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_arguments', models.JSONField(blank=True, default=dict, help_text='Default context/arguments for the workflow (e.g. {"auth_id": 1})')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to disable this schedule')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequency', models.ForeignKey(help_text='How often to run', on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_workflows', to='scheduler.frequency')),
                ('workflow', models.ForeignKey(help_text='Workflow to run on schedule', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_instances', to='service_builder.workflow')),
            ],
            options={
                'verbose_name': 'Scheduled Workflow',
                'verbose_name_plural': 'Scheduled Workflows',
            },
        ),
    ]
