# Generated by Django 5.2.7 on 2026-05-11 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='frequency',
            name='visible_to',
            field=models.ManyToManyField(blank=True, help_text='Users who can view and use this frequency.', related_name='visible_frequencies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledworkflow',
            name='visible_to',
            field=models.ManyToManyField(blank=True, help_text='Users who can view and use this scheduled workflow.', related_name='visible_scheduled_workflows', to=settings.AUTH_USER_MODEL),
        ),
    ]
